### ISSUE TITLE
Advice for testing Godot Game Engine

### ISSUE THREAD

**Issue by fire** [nxrighthere/BenchmarkNet#17]
Any suggestions?

**Comment by fire** [comment]
Should I convert to C++? Use C# godot or use gdscript from Godot Engine.

**Comment by nxrighthere** [comment]
If you mean testing Godot's ENet integration the best what you can do is to use Mono version and perform simulation using two instances of the application one for the server and one for the client.

I don't think that you will notice any significant difference since under the hood it's the same original ENet but with Godot sockets and some additional abstractions on top.
