### ISSUE TITLE
What about packet loss, and ping? (how fast packets delivered)

### ISSUE THREAD

**Issue by friuns2** [nxrighthere/BenchmarkNet#9]
What about packet loss, and ping? (how fast packets transmited)

Could be added to wiki page

**Comment by nxrighthere** [comment]
Simulation of lag/packet loss/etc is a random, thus, unpredictable results. Such information is irrelevant and can't not be compared between the networking libraries. If you want to simulate a bad network condition, you can use [Clumsy](http://jagt.github.io/clumsy/) for the experiments at your end.

**Comment by dzmitry-lahoda** [comment]
I think it would be very good test for games and unpredictable results are good. on average noise will be equal for all tests. so if loss will deviate than there is issues with udp library we wrap.
>> test message size larger than MTU via reliable UDP with network noise e.g. via https://jagt.github.io/clumsy/index.html or other

**Comment by nxrighthere** [comment]
Two things:

1. I'm performing each test manually 37x2 = 74 times in general, sitting and monitoring stats. I'm launching the application 74 times every update, capturing manually 37 screenshots, and then I'm updating 148 entries on the results page. In the BenchmarkNet 2.0, I'm planning to implement an automated benchmarking process, because I can't manually do this every time, and traffic lag/loss simulation requires to double this amount of manual work.
2. I already tried to perform tests with the simulation of a bad network condition, and every time I get absolutely different non-consistent results which don't show anything useful. It's just incomparable data that doesn't give any valuable information. We are creating games/application based on the accurate data and information sources, and mixing two programs for nothing is not how I work. If you don't agree, feel free to perform any tests you want. The source code is open, and the standalone application is available as well.

**Comment by nxrighthere** [comment]
@dzmitry-lahoda Check you email, please.

**Comment by inlife** [comment]
>What about packet loss, and ping? (how fast packets transmited)
I'm sorry, can you please elaborate more on the meaning behind this question? I want to understand your question properly.

**Comment by friuns2** [comment]
Some librares may handle packet transmision better than others, i don't think every library implement same retransmiting algorithms for packet loss. Also if some of them have bottleneck under high load they could send messages very late that why i would like to see averrage ping.

**Comment by nxrighthere** [comment]
> Some librares may handle packet transmision better than others, i don't think every library implement same retransmiting algorithms for packet loss.

They are doing almost the same job under the hood. The difference usually is numbers like ACK timeout intervals.

> And if you run test with network filter software that generates packet loss. results should be predictible, because you can set there how big packet loss will be.

No, it's not. You sending a reliable packet and it's lost, ACK was not received, the transport re-sending the packet, and it's lost again. Re-send attempts will happen over and over again randomly, and one particular networking library (or the same after re-running the test) will send more or less packet than another. Same drop rate doesn't guarantee the same percent of an overall count of lost packets.
